# -*- coding: utf-8 -*-
"""VietOCR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1udkS8XJkyd1VFdfpeoybO-wgPw9KbeHC

## Cài đặt thư viện
"""

!pip install -q vietocr
!pip install -U --force-reinstall pillow

!python -m pip install paddlepaddle
!python -m pip install paddleocr

import paddle
print("PaddlePaddle version:", paddle.__version__)
print("Compiled with CUDA:", paddle.device.is_compiled_with_cuda())  # sẽ ra False, đúng vì bản CPU

import paddleocr
print("PaddleOCR version:", paddleocr.__version__)

import os
os.kill(os.getpid(), 9)

"""## Khai báo mô hình VietOCR"""

# Load model VietOCR
from vietocr.tool.predictor import Predictor
from vietocr.tool.config import Cfg

config = Cfg.load_config_from_name('vgg_transformer')
config['device'] = 'cpu'
config['predictor']['beamsearch'] = False

vietocr_predictor = Predictor(config)

"""## Demo với ảnh 1 dòng"""

from PIL import Image, ImageDraw, ImageFont
import matplotlib.font_manager as fm

font_path = fm.findfont(fm.FontProperties(family='DejaVu Sans'))
font = ImageFont.truetype(font_path, 32)

def make_text_image(lines, width=600, line_height=50, padding=15):
    height = line_height * len(lines) + padding * 2
    img = Image.new("RGB", (width, height), "white")
    draw = ImageDraw.Draw(img)
    for i, line in enumerate(lines):
        draw.text((padding, padding + i * line_height), line, fill="black", font=font)
    return img

img_single_line = make_text_image(["Xin chào, tôi tên là Đạt."])
img_single_line

result_single = vietocr_predictor.predict(img_single_line)
print("Kết quả VietOCR:", result_single)

"""## Demo với ảnh 2 dòng"""

img_multi_line = make_text_image([
    "Xin chào, tôi tên là Đạt.",
    "Tôi đang giảng dạy tại Phenikaa University.",
    "Hôm nay chúng ta học về OCR tiếng Việt.",
])
img_multi_line

result_multi_wrong = vietocr_predictor.predict(img_multi_line)
print("Kết quả VietOCR (SAI vì đưa thẳng ảnh nhiều dòng):", result_multi_wrong)

"""## Data thực tế"""

# Code hiển thị ảnh
import matplotlib.pyplot as plt
from PIL import Image

def show_image(path_or_img, figsize=(5, 7), title=None):
    img = Image.open(path_or_img) if isinstance(path_or_img, str) else path_or_img
    plt.figure(figsize=figsize)
    plt.imshow(img)
    plt.axis('off')
    if title:
        plt.title(title)
    plt.show()

import gdown

file_id = "1MjLhbtFIjV7bOyrYfYNUsviJ1hO7wnRp"
gdown.download(f"https://drive.google.com/uc?id={file_id}", "new_image.png", quiet=False)

show_image("new_image.png", figsize=(4, 6), title="Ảnh mới")

"""## PaddleOCR"""

from paddleocr import PaddleOCR

ocr_cpu = PaddleOCR(
    text_detection_model_name="PP-OCRv6_medium_det",
    text_recognition_model_name="PP-OCRv6_medium_rec",
    use_doc_orientation_classify=False,
    use_doc_unwarping=False,
    use_textline_orientation=False,
    device="cpu",
    lang="vi",
    enable_mkldnn=False,
)

result = ocr_cpu.predict("new_image.png")

for res in result:
    res.print()
    res.save_to_img("output_new")
    res.save_to_json("output_new")

import glob
result_img = glob.glob("output_new/*.png") or glob.glob("output_new/*.jpg")
show_image(result_img[0], figsize=(5, 8), title="PaddleOCR")

import pandas as pd

rows = []
for res in result:
    for box, text, score in zip(res['dt_polys'], res['rec_texts'], res['rec_scores']):
        rows.append({
            "text": text,
            "score": round(float(score), 3),
            "x_min": int(box[:, 0].min()), "y_min": int(box[:, 1].min()),
            "x_max": int(box[:, 0].max()), "y_max": int(box[:, 1].max()),
        })

df_paddle_new = pd.DataFrame(rows)
df_paddle_new

"""## Kết hợp PaddleOCR + VietOCR"""

# ===== 2. Load PaddleOCR (detect) — TẮT preprocessing vì ảnh scan đã thẳng sẵn =====
from paddleocr import PaddleOCR

ocr_cpu = PaddleOCR(
    text_detection_model_name="PP-OCRv6_medium_det",
    text_recognition_model_name="PP-OCRv6_medium_rec",
    use_doc_orientation_classify=False,
    use_doc_unwarping=False,
    use_textline_orientation=True,
    device="cpu",
    lang="vi",
    enable_mkldnn=False,
)

# ===== 4. Detect box =====
result = ocr_cpu.predict("new_image.png")

# ===== 5. Recognize từng box bằng VietOCR (giữ nguyên) =====
from PIL import Image

img_new = Image.open("new_image.png").convert("RGB")

boxes = []
texts = []

for res in result:
    for box in res['dt_polys']:
        x_min = int(box[:, 0].min())
        y_min = int(box[:, 1].min())
        x_max = int(box[:, 0].max())
        y_max = int(box[:, 1].max())

        crop = img_new.crop((x_min, y_min, x_max, y_max))
        text = vietocr_predictor.predict(crop)

        boxes.append((x_min, y_min, x_max, y_max))
        texts.append(text)

# ===== 6. Chỉ vẽ box, không vẽ text =====
from PIL import ImageDraw

img_draw = img_new.copy()
draw = ImageDraw.Draw(img_draw)

for (x_min, y_min, x_max, y_max) in boxes:
    draw.rectangle([x_min, y_min, x_max, y_max], outline="red", width=1)

show_image(img_draw, figsize=(6, 9), title="PaddleOCR detect boxes")

# ===== 7. Bảng kết quả =====
import pandas as pd

df_result = pd.DataFrame({
    "text": texts,
    "x_min": [b[0] for b in boxes],
    "y_min": [b[1] for b in boxes],
    "x_max": [b[2] for b in boxes],
    "y_max": [b[3] for b in boxes],
})
df_result